### PR TITLE
Should only allow portrait mode

### PR DESCRIPTION
**Pull request by ii887522**
I saw the design only for portrait mode, this PR will prevent users from seeing broken UI due to phone rotation

### CODE REVIEW

**Comment by HatataMakuna** [comment]
If only allow portrait mode, the admin portal might not be scrollable

**Comment by ii887522** [comment]
I have removed the orientation restrictions in admin portal, so far I tested myself the user side can prevent landscape mode, not sure about the admin side as I do not have an admin account 🥲

**Comment by HatataMakuna** [comment]
Here's the admin account if you want to test it:
Email: jmadmin@tarc.edu.my
Password: 87654321

I only provide the apk file in the repo, so there's no plan for iOS support for now.

**Comment by ii887522** [comment]
I have self tested user side only allow portrait mode and admin side only allow landscape mode since portrait mode can cause rendering error when navigating to the first page in the admin portal. You try it on your side if there is no problem then I think can merge.

btw, after user logs out from admin portal and logs in back again cannot log in. I checkout your master branch oso got this problem sometimes pops up error message but most of the time error message just flashing cant see clearly. I think that is another issue need to solve separately.

**Comment by HatataMakuna** [comment]
Logging out from admin and log back in one I think is the UI problem, since the admin portal is from a template, therefore it's quite difficult to solve it. I open another issue #41 for that.

**Pull request merged**
